

let PDFDocument;
try {
  PDFDocument = require("pdfkit");
} catch (e) {

console.warn("pdfkit not installed — PDF generation disabled:", e.message);
}

const fs = require("fs");
const path = require("path");

const sanitize = (s) => {
  if (typeof s !== "string") return "";
  
  return s
    .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, "")
    .slice(0, 4000);
};

const safeVal = (v, fallback = "—") =>
  v === null || v === undefined || v === "" ? fallback : String(v);

const slugify = (s) =>
  String(s || "report")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40) || "report";

const renderCover = (doc, { user, appliance, analysis, template }) => {
  doc.fontSize(22).fillColor("#000").text("AI Home Maintenance — Diagnostic Report");
  doc.moveDown(0.5);
  doc.fontSize(11).fillColor("#666").text(`Template: ${template}`);
  doc.text(`Generated: ${new Date().toISOString()}`);
  if (user && (user.name || user.email)) {
    doc.text(`Prepared for: ${safeVal(user.name)} (${safeVal(user.email)})`);
  }
  doc.moveDown(1);

  doc.fillColor("#000").fontSize(14).text("Appliance");
  doc.moveDown(0.3);
  const a = appliance || {};
  doc.fontSize(11)
    .text(`Name:        ${safeVal(a.name)}`)
    .text(`Type:        ${safeVal(a.type)}`)
    .text(`Brand:       ${safeVal(a.brand)}`)
    .text(`Model:       ${safeVal(a.model)}`)
    .text(`Serial:      ${safeVal(a.serialNumber)}`)
    .text(`Location:    ${safeVal(a.location)}`)
    .text(`Installed:   ${safeVal(a.installedAt || a.purchaseDate)}`);
  doc.moveDown(1);
  return doc;
};

const renderAnalysis = (doc, analysis, { includeRepairSteps }) => {
  const a = (analysis && analysis.analysis) || {};
  doc.fontSize(14).text("AI Diagnosis");
  doc.moveDown(0.3);
  doc.fontSize(11);

  if (analysis) {
    if (analysis.aiModel) doc.text(`Model:        ${safeVal(analysis.aiModel)}${analysis.isMock ? " (mock)" : ""}`);
    if (analysis.processingTime) doc.text(`Latency:      ${safeVal(analysis.processingTime)} ms`);
  }
  if (a.issue)          doc.text(`Issue:        ${safeVal(a.issue)}`);
  if (a.severity)       doc.text(`Severity:     ${safeVal(a.severity)}`);
  if (a.confidence !== undefined && a.confidence !== null) {
    doc.text(`Confidence:   ${safeVal(a.confidence)}%`);
  }
  if (a.rootCause)      doc.text(`Root cause:   ${sanitize(a.rootCause)}`);
  if (a.solution)       doc.text(`Solution:     ${sanitize(a.solution)}`);

  if (Array.isArray(a.probableCauses) && a.probableCauses.length > 0) {
    doc.moveDown(0.5);
    doc.fontSize(12).text("Probable causes:");
    doc.fontSize(11);
    for (const c of a.probableCauses) {
      const label = typeof c === "string" ? c : safeVal(c.cause);
      const pct = typeof c === "object" && c.probability !== undefined ? ` (${c.probability}%)` : "";
      doc.text(`• ${label}${pct}`);
    }
  }

  if (Array.isArray(a.recommendations) && a.recommendations.length > 0) {
    doc.moveDown(0.5);
    doc.fontSize(12).text("Recommendations:");
    doc.fontSize(11);
    for (const r of a.recommendations) doc.text(`• ${safeVal(r)}`);
  }

  if (includeRepairSteps && Array.isArray(a.repairSteps) && a.repairSteps.length > 0) {
    doc.moveDown(0.5);
    doc.fontSize(12).text("Repair steps:");
    doc.fontSize(11);
    a.repairSteps.forEach((s, i) => doc.text(`${i + 1}. ${safeVal(s)}`));
  }

  if (Array.isArray(a.matchedRules) && a.matchedRules.length > 0) {
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor("#666").text(`Matched rules: ${a.matchedRules.join(", ")}`);
    doc.fillColor("#000");
  }
  doc.moveDown(1);
  return doc;
};

const renderFooter = (doc) => {
  doc.fontSize(9).fillColor("#999").text(
    "This report is generated by an AI system and is intended as guidance only. " +
    "Always consult a qualified technician before performing repairs.",
    { align: "center" }
  );
  return doc;
};

const buildPdfBuffer = ({ user, appliance, analysis, template }) => {
  return new Promise((resolve, reject) => {
    if (!PDFDocument) {
      return reject(new Error("PDF generation unavailable — pdfkit not installed"));
    }
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    try {
      renderCover(doc, { user, appliance, analysis, template });
      renderAnalysis(doc, analysis, {
        includeRepairSteps: template === "technician",
      });
      if (template === "insurance") {
        doc.fontSize(14).text("Insurance claim summary");
        doc.moveDown(0.3);
        doc.fontSize(11)
          .text(`Incident date: ${safeVal(analysis && analysis.date || new Date().toISOString())}`)
          .text(`Damage type:   ${safeVal(appliance && appliance.type)}`)
          .text(`Claimant:      ${safeVal(user && user.name)}`);
      }
      renderFooter(doc);
      doc.end();
    } catch (e) {
      reject(e);
    }
  });
};

const streamReport = (res, payload) => {
  if (!PDFDocument) {
    res.status(503).json({
      success: false,
      error: { code: "PDF_UNAVAILABLE", message: "PDF generation is not available" },
    });
    return;
  }

  const doc = new PDFDocument({ margin: 50, size: "A4" });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="report-${Date.now()}.pdf"`
  );
  doc.pipe(res);

  renderCover(doc, payload);
  renderAnalysis(doc, payload.analysis, { includeRepairSteps: true });
  renderFooter(doc);

  doc.end();
};

const generateReport = async ({
  user,
  appliance,
  analysis,
  outputDir,
  template: rawTemplate,
}) => {
  const template = ["executive", "technician", "insurance"].includes(rawTemplate)
    ? rawTemplate
    : "executive";

  const dir = outputDir || path.join(process.cwd(), "tmp", "reports");
  fs.mkdirSync(dir, { recursive: true });

  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const fileName = `${slugify(appliance && appliance.name)}-${template}-${stamp}.pdf`;
  const filePath = path.join(dir, fileName);

  const buf = await buildPdfBuffer({ user, appliance, analysis, template });
  fs.writeFileSync(filePath, buf);

  return { filePath, fileName, fileSize: buf.length };
};

const verifyPdfFile = async (filePath) => {
  if (!filePath || typeof filePath !== "string") {
    throw new Error("verifyPdfFile: filePath required");
  }
  const stat = fs.statSync(filePath);
  if (stat.size < 200) {
    throw new Error(`verifyPdfFile: file too small (${stat.size} bytes)`);
  }
  const fd = fs.openSync(filePath, "r");
  try {
    const header = Buffer.alloc(5);
    fs.readSync(fd, header, 0, 5, 0);
    const magic = header.toString("latin1");
    if (magic !== "%PDF-") {
      throw new Error(`verifyPdfFile: bad magic header (got ${JSON.stringify(magic)})`);
    }
  } finally {
    fs.closeSync(fd);
  }
};

module.exports = {
  streamReport,
  generateReport,
  verifyPdfFile,
  
  generate: generateReport,
};
