import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Share,
  Alert,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Colors as COLORS, Spacing as SIZES } from '../constants/theme';
import pdfService from '../services/pdfService';

const DiagnosticResultScreen = ({ route, navigation }) => {
  const { result, testType } = route.params;
  const { diagnosis } = result;

  const getSeverityColor = (severity) => {
    switch (severity?.toLowerCase()) {
      case 'critical':
        return '#D32F2F';
      case 'high':
        return '#F44336';
      case 'medium':
        return '#FF9800';
      case 'low':
        return '#4CAF50';
      default:
        return COLORS.gray;
    }
  };

  const getUrgencyIcon = (urgency) => {
    switch (urgency) {
      case 'immediate':
        return 'alert-circle';
      case 'within-week':
        return 'time';
      case 'within-month':
        return 'calendar';
      default:
        return 'checkmark-circle';
    }
  };

  const getUrgencyText = (urgency) => {
    switch (urgency) {
      case 'immediate':
        return 'Immediate Action Required';
      case 'within-week':
        return 'Fix Within a Week';
      case 'within-month':
        return 'Fix Within a Month';
      default:
        return 'Routine Maintenance';
    }
  };

  const handleShare = async () => {
    try {
      const message = `
🔧 Diagnostic Report - ${testType}

📋 Issue: ${diagnosis.issue}
⚠️ Severity: ${diagnosis.severity}
🎯 Confidence: ${diagnosis.confidence}%

🔍 Root Cause:
${diagnosis.rootCause}

💡 Solution:
${diagnosis.solution}

${diagnosis.estimatedCost ? `💰 Estimated Cost: ₹${diagnosis.estimatedCost.min} - ₹${diagnosis.estimatedCost.max}` : ''}

Generated by AI Home Maintenance Assistant
      `.trim();

      await Share.share({ message });
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  return (
    <View style={styles.container}>
      {}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
          <Ionicons name="arrow-back" size={24} color={COLORS.white} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Diagnostic Result</Text>
        <TouchableOpacity
          onPress={() => navigation.navigate('PdfReport', {
            analysisId: result._id,
            deviceName: result.deviceName,
            deviceType: result.deviceType,
            analysis: result,
          })}
          style={styles.shareButton}
        >
          <Ionicons name="document-text-outline" size={22} color={COLORS.white} />
        </TouchableOpacity>
        <TouchableOpacity
          onPress={() => navigation.navigate('RulesTrace', { deviceType: result.deviceType })}
          style={styles.shareButton}
        >
          <Ionicons name="git-branch-outline" size={22} color={COLORS.white} />
        </TouchableOpacity>
        <TouchableOpacity onPress={handleShare} style={styles.shareButton}>
          <Ionicons name="share-outline" size={24} color={COLORS.white} />
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.content}>
        {}
        <View style={styles.badgeContainer}>
          <View style={styles.badge}>
            <Text style={styles.badgeText}>{testType}</Text>
          </View>
        </View>

        {}
        <View style={[styles.severityCard, { borderLeftColor: getSeverityColor(diagnosis.severity) }]}>
          <View style={styles.severityHeader}>
            <Ionicons 
              name="warning" 
              size={32} 
              color={getSeverityColor(diagnosis.severity)} 
            />
            <View style={styles.severityInfo}>
              <Text style={styles.severityLabel}>Severity Level</Text>
              <Text style={[styles.severityValue, { color: getSeverityColor(diagnosis.severity) }]}>
                {diagnosis.severity}
              </Text>
            </View>
            <View style={styles.confidenceBadge}>
              <Text style={styles.confidenceText}>{diagnosis.confidence}%</Text>
              <Text style={styles.confidenceLabel}>Confidence</Text>
            </View>
          </View>
        </View>

        {}
        <View style={styles.card}>
          <View style={styles.cardHeader}>
            <Ionicons name="alert-circle-outline" size={24} color={COLORS.primary} />
            <Text style={styles.cardTitle}>Identified Issue</Text>
          </View>
          <Text style={styles.issueText}>{diagnosis.issue}</Text>
        </View>

        {}
        <View style={styles.urgencyCard}>
          <Ionicons 
            name={getUrgencyIcon(diagnosis.urgency)} 
            size={24} 
            color={diagnosis.urgency === 'immediate' ? COLORS.error : COLORS.warning} 
          />
          <Text style={styles.urgencyText}>{getUrgencyText(diagnosis.urgency)}</Text>
        </View>

        {}
        {diagnosis.affectedComponents && diagnosis.affectedComponents.length > 0 && (
          <View style={styles.card}>
            <View style={styles.cardHeader}>
              <Ionicons name="construct-outline" size={24} color={COLORS.primary} />
              <Text style={styles.cardTitle}>Affected Components</Text>
            </View>
            {diagnosis.affectedComponents.map((component, index) => (
              <View key={index} style={styles.componentItem}>
                <Ionicons name="ellipse" size={8} color={COLORS.primary} />
                <Text style={styles.componentText}>{component}</Text>
              </View>
            ))}
          </View>
        )}

        {}
        {diagnosis.rootCause && (
          <View style={styles.card}>
            <View style={styles.cardHeader}>
              <Ionicons name="search-outline" size={24} color={COLORS.primary} />
              <Text style={styles.cardTitle}>Root Cause</Text>
            </View>
            <Text style={styles.descriptionText}>{diagnosis.rootCause}</Text>
          </View>
        )}

        {}
        <View style={styles.card}>
          <View style={styles.cardHeader}>
            <Ionicons name="bulb-outline" size={24} color={COLORS.success} />
            <Text style={styles.cardTitle}>Recommended Solution</Text>
          </View>
          <Text style={styles.descriptionText}>{diagnosis.solution}</Text>
          
          {diagnosis.diyPossible !== undefined && (
            <View style={styles.diyBadge}>
              <Ionicons 
                name={diagnosis.diyPossible ? "checkmark-circle" : "close-circle"} 
                size={20} 
                color={diagnosis.diyPossible ? COLORS.success : COLORS.error} 
              />
              <Text style={styles.diyText}>
                {diagnosis.diyPossible ? 'DIY Possible' : 'Professional Help Required'}
              </Text>
            </View>
          )}
        </View>

        {}
        {diagnosis.estimatedCost && (
          <View style={styles.costCard}>
            <Ionicons name="cash-outline" size={24} color={COLORS.primary} />
            <View style={styles.costInfo}>
              <Text style={styles.costLabel}>Estimated Repair Cost</Text>
              <Text style={styles.costValue}>
                ₹{diagnosis.estimatedCost.min} - ₹{diagnosis.estimatedCost.max}
              </Text>
            </View>
          </View>
        )}

        {}
        {diagnosis.preventiveMeasures && diagnosis.preventiveMeasures.length > 0 && (
          <View style={styles.card}>
            <View style={styles.cardHeader}>
              <Ionicons name="shield-checkmark-outline" size={24} color={COLORS.primary} />
              <Text style={styles.cardTitle}>Preventive Measures</Text>
            </View>
            {diagnosis.preventiveMeasures.map((measure, index) => (
              <View key={index} style={styles.measureItem}>
                <Ionicons name="checkmark" size={20} color={COLORS.success} />
                <Text style={styles.measureText}>{measure}</Text>
              </View>
            ))}
          </View>
        )}

        {}
        {(result.matchedRules?.length || result.analysis?.ruleTrace?.length) ? (
          <View style={styles.card}>
            <View style={styles.cardHeader}>
              <Ionicons name="git-branch-outline" size={24} color={COLORS.primary} />
              <Text style={styles.cardTitle}>Rule Trace</Text>
            </View>
            <Text style={styles.descriptionText}>
              {result.matchedRules?.length || 0} rule(s) fired and shaped this diagnosis.
            </Text>
            {(result.analysis?.ruleTrace || []).filter((r) => r.matched).slice(0, 5).map((r) => (
              <View key={r.id} style={styles.componentItem}>
                <Ionicons name="checkmark-circle" size={14} color={COLORS.success} />
                <Text style={styles.componentText}>
                  {r.id} — {r.name}
                </Text>
              </View>
            ))}
            <TouchableOpacity
              style={styles.secondaryButton}
              onPress={() => navigation.navigate('RulesTrace', { deviceType: result.deviceType })}
            >
              <Ionicons name="open-outline" size={16} color={COLORS.primary} />
              <Text style={[styles.secondaryButtonText, { color: COLORS.primary }]}>
                View full rule trace
              </Text>
            </TouchableOpacity>
          </View>
        ) : null}

        {}
        <View style={styles.actionButtons}>
          <TouchableOpacity 
            style={styles.primaryButton}
            onPress={() => navigation.navigate('DiagnosticHome')}
          >
            <Ionicons name="home-outline" size={20} color={COLORS.white} />
            <Text style={styles.primaryButtonText}>Back to Home</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={styles.secondaryButton}
            onPress={() => navigation.navigate('DiagnosticHome')}
          >
            <Ionicons name="time-outline" size={20} color={COLORS.primary} />
            <Text style={styles.secondaryButtonText}>Run Another Test</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background
  },
  header: {
    backgroundColor: COLORS.primary,
    padding: SIZES.lg,
    paddingTop: SIZES.lg * 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between'
  },
  backButton: {
    marginRight: 16
  },
  headerTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.white
  },
  shareButton: {
    padding: 8
  },
  content: {
    flex: 1,
    padding: SIZES.lg
  },
  badgeContainer: {
    alignItems: 'center',
    marginBottom: 16
  },
  badge: {
    backgroundColor: COLORS.primary + '20',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20
  },
  badgeText: {
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: '600'
  },
  severityCard: {
    backgroundColor: COLORS.white,
    padding: SIZES.lg,
    borderRadius: 12,
    marginBottom: 16,
    borderLeftWidth: 6,
    elevation: 2
  },
  severityHeader: {
    flexDirection: 'row',
    alignItems: 'center'
  },
  severityInfo: {
    flex: 1,
    marginLeft: 16
  },
  severityLabel: {
    fontSize: 12,
    color: COLORS.gray,
    marginBottom: 4
  },
  severityValue: {
    fontSize: 24,
    fontWeight: 'bold'
  },
  confidenceBadge: {
    alignItems: 'center'
  },
  confidenceText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.primary
  },
  confidenceLabel: {
    fontSize: 10,
    color: COLORS.gray
  },
  card: {
    backgroundColor: COLORS.white,
    padding: SIZES.lg,
    borderRadius: 12,
    marginBottom: 16,
    elevation: 1
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.text,
    marginLeft: 12
  },
  issueText: {
    fontSize: 16,
    color: COLORS.text,
    lineHeight: 24
  },
  urgencyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF3E0',
    padding: SIZES.lg,
    borderRadius: 12,
    marginBottom: 16
  },
  urgencyText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.text,
    marginLeft: 12
  },
  componentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    paddingLeft: 8
  },
  componentText: {
    fontSize: 14,
    color: COLORS.text,
    marginLeft: 12
  },
  descriptionText: {
    fontSize: 14,
    color: COLORS.text,
    lineHeight: 22
  },
  diyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.lightGray
  },
  diyText: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.text,
    marginLeft: 8
  },
  costCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.success + '15',
    padding: SIZES.lg,
    borderRadius: 12,
    marginBottom: 16
  },
  costInfo: {
    marginLeft: 16
  },
  costLabel: {
    fontSize: 12,
    color: COLORS.gray,
    marginBottom: 4
  },
  costValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.text
  },
  measureItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 12
  },
  measureText: {
    flex: 1,
    fontSize: 14,
    color: COLORS.text,
    marginLeft: 12,
    lineHeight: 20
  },
  actionButtons: {
    marginTop: 8,
    marginBottom: 24
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    padding: 16,
    borderRadius: 12,
    marginBottom: 12
  },
  primaryButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.primary
  },
  secondaryButtonText: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8
  }
});

export default DiagnosticResultScreen;
